INSERT INTO UniversityApplications (UniversityID, StatusID, Motivation, Date, ReviewerID_UserID, ReviewerComment)
VALUES
(21, 3, 'Walter Sisulu University is dedicated to providing quality education and fostering social responsibility. Our commitment to empowering students from diverse backgrounds aligns closely with the goals of your bursary program. We believe that by partnering with your program, we can make a meaningful difference in the lives of our students.', '2021-03-01', 5, 'Congratulations! Your application has been approved.'),
(22, 3, 'North-West University, with its emphasis on research and its commitment to academic excellence, is dedicated to preparing students for success in a rapidly changing world. By joining your bursary program, we seek to extend our impact and support more students in need. We believe that our innovative programs and our focus on student-centered learning make us a strong candidate for your program.', '2021-09-04', 8, 'Congratulations! Your application has been approved.'),
(23, 3, 'The University of Free State, with its focus on diversity and its commitment to excellence, is dedicated to promoting inclusivity and social justice. By partnering with your bursary program, we aim to extend our reach and provide greater opportunities for our students to succeed. We believe that our strong community engagement initiatives and our dedication to producing well-rounded graduates make us an ideal partner for your program.', '2022-02-14', 7, 'Congratulations! Your application has been approved.'),

(24, 4, 'Sefako Makgatho Health Sciences University is dedicated to advancing health sciences education and research. Our programs are designed to prepare students for careers in health professions, and we believe that by joining your bursary program, we can extend our reach and support more students in need. We are confident that our innovative approach to health sciences education and our commitment to community service make us a strong candidate for your program.', '2022-03-04', 5, 'We regret to inform you that your application has been rejected. Although your institution has commendable programs, we have limited slots available, and we believe other applicants better fit our current criteria.'),
(25, 4, 'Sol Plaatje University, with its focus on innovation and its commitment to academic excellence, is dedicated to preparing students for success in a rapidly changing world. By joining your bursary program, we aim to extend our impact and support more students in need. We believe that our unique programs and our dedication to student success make us an ideal partner for your program.', '2022-06-05', 7, 'We regret to inform you that your application has been rejected. While your institution has promising programs, we have selected other applicants whose profiles better align with our current needs.'),

(26, 3, 'The University of South Africa (UNISA), with its dedication to open and distance learning, is committed to providing accessible education to all South Africans. By joining your bursary program, we aim to extend our reach and support more students in need. We believe that our flexible learning options and our commitment to student support make us an ideal partner for your program.', '2023-01-15', 8, 'Congratulations! Your application has been approved.'),
(25, 3, 'Sol Plaatje University is dedicated to providing access to higher education for all students, regardless of their financial circumstances. We believe that participation in your bursary program will enable us to further this mission and support deserving students in achieving their academic goals.', '2023-01-30', 7, 'Congratulations! Your application has been approved.'),

(27, 4, 'South African College of Music, as a renowned institution for music education, is dedicated to nurturing musical talent and promoting cultural enrichment. By joining your bursary program, we aim to extend our impact and support more aspiring musicians. We believe that our innovative programs and our commitment to artistic excellence make us a strong candidate for your program.', '2023-06-18', 5, 'We regret to inform you that your application has been rejected. While your institution has commendable programs, we have selected other applicants whose profiles better align with our current needs.'),

(28, 2, 'Regenesys Business School, with its focus on business education and its commitment to developing ethical leaders, is dedicated to preparing students for success in the global marketplace. By joining your bursary program, we aim to extend our impact and support more aspiring business leaders. We believe that our innovative programs and our emphasis on practical learning make us a strong candidate for your program.', '2023-10-27', 8, 'Your application is currently under review.'),
(29, 2, 'Pearson Institute of Higher Education, with its focus on career-oriented education and its commitment to student success, is dedicated to preparing students for the demands of the modern workplace. By joining your bursary program, we aim to extend our reach and support more aspiring professionals. We believe that our industry partnerships and our focus on employability make us an ideal partner for your program.', '2023-12-10', 8, 'Your application is currently under review.'),
(30, 2, 'African Leadership Academy, with its focus on leadership development and its commitment to fostering positive change in Africa, is dedicated to preparing young leaders for success in a rapidly changing world. By joining your bursary program, we aim to extend our impact and support more aspiring change-makers. We believe that our innovative programs and our emphasis on ethical leadership make us a strong candidate for your program.', '2023-12-15', 5, 'Your application is currently under review.'),

(31, 1, 'African School of Economics, with its focus on economics education and its commitment to promoting economic development in Africa, is dedicated to preparing students for careers in economics and related fields. By joining your bursary program, we aim to extend our reach and support more aspiring economists. We believe that our rigorous academic programs and our focus on policy-relevant research make us an ideal partner for your program.', '2024-01-08', 7, 'Your application has been submitted and is awaiting review.'),
(32, 1, 'AFDA, The School for the Creative Economy, with its focus on creative education and its commitment to fostering artistic talent, is dedicated to preparing students for careers in the creative industries. By joining your bursary program, we aim to extend our impact and support more aspiring artists. We believe that our innovative programs and our emphasis on hands-on learning make us a strong candidate for your program.', '2024-02-10', 5, 'Your application has been submitted and is awaiting review.'),
(33, 1, 'Aros, with its focus on vocational training and its commitment to preparing students for careers in various industries, is dedicated to providing practical education and skills development. By joining your bursary program, we aim to extend our reach and support more aspiring professionals. We believe that our industry-aligned programs and our focus on experiential learning make us an ideal partner for your program.', '2024-01-09', 7, 'Your application has been submitted and is awaiting review.');
